export const dummyUserData = [
  {
    answerMethod: "INPUT_TEXT",
    examCode: "a123456786",
    userName: "김철수",
    phoneNumber: "01012345678",
    class: "2",
    studentNumber: "4",
  },
  {
    answerMethod: "INPUT_OMR",
    examCode: "a123456787",
    userName: "이영희",
    phoneNumber: "01098765432",
    class: "2",
    studentNumber: "5",
  },
  {
    answerMethod: "INPUT_EXCEL",
    examCode: "a123456788",
    userName: "정재은",
    phoneNumber: "01098765432",
    class: "2",
    studentNumber: "6",
  },
];

export const dummyOmrData = [
  {
    answerMethod: "INPUT_TEXT",
    subject: "korean",
    userName: "김철수",
    class: "2",
    studentNumber: "4",
    phoneNumber: "01012345678",
    selectedSubjects: "1",
    answers: ["1", "2"],
  },
  {
    answerMethod: "INPUT_OMR",
    subject: "korean",
    userName: "이영희",
    class: "2",
    studentNumber: "4",
    phoneNumber: "01012345678",
    selectedSubjects: "1",
    answers: ["1", "2"],
  },
  {
    answerMethod: "INPUT_EXCEL",
    subject: "english",
    userName: "정재은",
    class: "2",
    studentNumber: "6",
    phoneNumber: "01098765434",
    answers: ["1", "2"],
  },
  {
    answerMethod: "INPUT_EXCEL",
    subject: "korean",
    userName: "정재은",
    class: "2",
    studentNumber: "6",
    phoneNumber: "01098765431",
    answers: ["1", "2"],
  },
  {
    answerMethod: "INPUT_TEXT",
    subject: "math",
    userName: "김철수",
    class: "2",
    studentNumber: "4",
    phoneNumber: "01012345678",
    selectedSubjects: "1",
    answers: ["1", "2"],
  },
  {
    answerMethod: "INPUT_OMR",
    subject: "math",
    userName: "이영희",
    class: "2",
    studentNumber: "4",
    phoneNumber: "01012345671",
    selectedSubjects: "1",
    answers: ["1", "2"],
  },
  {
    answerMethod: "INPUT_EXCEL",
    subject: "math",
    userName: "정재은",
    class: "2",
    studentNumber: "6",
    phoneNumber: "01098765431",
    answers: ["1", "2"],
  },
];
