export const countrySelect = [
  { value: '', label: 'Nationality' },
  { value: '아프가니스탄', label: 'AFGHANISTAN' },
  { value: '알바니아', label: 'ALBANIA' },
  { value: '알제리', label: 'ALGERIA' },
  { value: '미국령 사모아', label: 'AMERICAN SAMOA' },
  { value: '안도라', label: 'ANDORRA' },
  { value: '앙골라', label: 'ANGOLA' },
  { value: '앙귈라', label: 'ANGUILLA' },
  { value: '안타티카', label: 'ANTARCTICA' },
  { value: '앤티가 바부다', label: 'ANTIGUA AND BARBUDA' },
  { value: '아르헨티나', label: 'ARGENTINA' },
  { value: '아르메니아', label: 'ARMENIA' },
  { value: '아루바', label: 'ARUBA' },
  { value: '오스트레일리아', label: 'AUSTRALIA' },
  { value: '오스트리아', label: 'AUSTRIA' },
  { value: '아제르바이잔', label: 'AZERBAIJAN' },
  { value: '바하마', label: 'BAHAMAS' },
  { value: '바레인', label: 'BAHRAIN' },
  { value: '방글라데시', label: 'BANGLADESH' },
  { value: '바베이도스', label: 'BARBADOS' },
  { value: '벨라루스', label: 'BELARUS' },
  { value: '벨기에', label: 'BELGIUM' },
  { value: '벨리즈', label: 'BELIZE' },
  { value: '베냉', label: 'BENIN' },
  { value: '버뮤다', label: 'BERMUDA' },
  { value: '부탄', label: 'BHUTAN' },
  { value: '볼리비아', label: 'BOLIVIA' },
  { value: '보스니아 헤르체고비나', label: 'BOSNIA HERCEGOVINA' },
  { value: '보츠와나', label: 'BOTSWANA' },
  { value: '브라질', label: 'BRAZIL' },
  { value: '브루나이 다루살람', label: 'BRUNEI DARUSSALAM' },
  { value: '불가리아', label: 'BULGARIA' },
  { value: '부르키나파소', label: 'BURKINA FASO' },
  { value: '부룬디', label: 'BURUNDI' },
  { value: '캄보디아', label: 'CAMBODIA' },
  { value: '카메룬', label: 'CAMEROON' },
  { value: '캐나다', label: 'CANADA' },
  { value: '카보 베르데', label: 'CAPE VERDE' },
  { value: '케이맨제도', label: 'CAYMAN ISLANDS' },
  { value: '중앙 아프리카 공화국', label: 'CENTRAL AFRICAN REPUBLIC' },
  { value: '차드', label: 'CHAD' },
  { value: '칠레', label: 'CHILE' },
  { value: '중국', label: 'CHINA' },
  { value: '크리스마스 섬', label: 'CHRISTMAS ISLAND' },
  { value: '코코스 (킬링) 제도', label: 'COCOS (KEELING) ISLANDS' },
  { value: '콜롬비아', label: 'COLOMBIA' },
  { value: '코모로', label: 'COMOROS' },
  { value: '콩고', label: 'CONGO' },
  { value: '쿡제도', label: 'COOK ISLANDS' },
  { value: '코스타리카', label: 'COSTA RICA' },
  { value: '크로아티아', label: 'CROATIA' },
  { value: '쿠바', label: 'CUBA' },
  { value: '키프로스', label: 'CYPRUS' },
  { value: '체코 공화국', label: 'CZECH REPUBLIC' },
  { value: '덴마크', label: 'DENMARK' },
  { value: '지부티', label: 'DJIBOUTI' },
  { value: '도미니카', label: 'DOMINICA' },
  { value: '도미니카 공화국', label: 'DOMINICAN REPUBLIC' },
  { value: '동티모르', label: 'EAST TIMOR' },
  { value: '에콰도르', label: 'ECUADOR' },
  { value: '이집트', label: 'EGYPT' },
  { value: '엘살바도르', label: 'EL SALVADOR' },
  { value: '적도 기니', label: 'EQUATORIAL GUINEA' },
  { value: '에리트레아', label: 'ERITREA' },
  { value: '에스토니아', label: 'ESTONIA' },
  { value: '에스와티니', label: 'ESWATINI' },
  { value: '에티오피아', label: 'ETHIOPIA' },
  { value: '포클랜드 제도 (말비나스)', label: 'FALKLAND ISLANDS (MALVINAS)' },
  { value: '페로 제도', label: 'FAROE ISLANDS' },
  { value: '피지', label: 'FIJI' },
  { value: '핀란드', label: 'FINLAND' },
  { value: '프랑스', label: 'FRANCE' },
  { value: '프랑스령 기아나', label: 'FRENCH GUIANA' },
  { value: '프랑스령 폴리네시아', label: 'FRENCH POLYNESIA' },
  { value: '프랑스령 남부 지역', label: 'FRENCH SOUTHERN TERRITORIES' },
  { value: '가봉', label: 'GABON' },
  { value: '감비아', label: 'GAMBIA' },
  { value: '조지아', label: 'GEORGIA' },
  { value: '독일', label: 'GERMANY' },
  { value: '가나', label: 'GHANA' },
  { value: '지브롤터', label: 'GIBRALTAR' },
  { value: '그리스', label: 'GREECE' },
  { value: '그린란드', label: 'GREENLAND' },
  { value: '그레나다', label: 'GRENADA' },
  { value: '과들루프', label: 'GUADELOUPE' },
  { value: '괌', label: 'GUAM' },
  { value: '과테말라', label: 'GUATEMALA' },
  { value: '건지', label: 'GUERNSEY' },
  { value: '기니', label: 'GUINEA' },
  { value: '기니비사우', label: 'GUINEA-BISSAU' },
  { value: '가이아나', label: 'GUYANA' },
  { value: '아이티', label: 'HAITI' },
  { value: '허드 및 맥도날드 제도', label: 'HEARD ISLAND AND MCDONALD ISLANDS' },
  { value: '온두라스', label: 'HONDURAS' },
  { value: '홍콩', label: 'HONG KONG' },
  { value: '헝가리', label: 'HUNGARY' },
  { value: '아이슬란드', label: 'ICELAND' },
  { value: '인도', label: 'INDIA' },
  { value: '인도네시아', label: 'INDONESIA' },
  { value: '이란', label: 'IRAN' },
  { value: '이라크', label: 'IRAQ' },
  { value: '아일랜드', label: 'IRELAND' },
  { value: '맨섬', label: 'ISLE OF MAN' },
  { value: '이스라엘', label: 'ISRAEL' },
  { value: '이탈리아', label: 'ITALY' },
  { value: '자메이카', label: 'JAMAICA' },
  { value: '일본', label: 'JAPAN' },
  { value: '저지', label: 'JERSEY' },
  { value: '요르단', label: 'JORDAN' },
  { value: '카자흐스탄', label: 'KAZAKHSTAN' },
  { value: '케냐', label: 'KENYA' },
  { value: '키리바시', label: 'KIRIBATI' },
  { value: '조선 민주주의 인민 공화국', label: "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF" },
  { value: '대한민국', label: 'KOREA, REPUBLIC OF' },
  { value: '쿠웨이트', label: 'KUWAIT' },
  { value: '키르기스스탄', label: 'KYRGYZSTAN' },
  { value: '라오스', label: 'LAOS' },
  { value: '라트비아', label: 'LATVIA' },
  { value: '레바논', label: 'LEBANON' },
  { value: '레소토', label: 'LESOTHO' },
  { value: '라이베리아', label: 'LIBERIA' },
  { value: '리비아', label: 'LIBYA' },
  { value: '리히텐슈타인', label: 'LIECHTENSTEIN' },
  { value: '리투아니아', label: 'LITHUANIA' },
  { value: '룩셈부르크', label: 'LUXEMBOURG' },
  { value: '마카오', label: 'MACAU' },
  { value: '북마케도니아', label: 'MACEDONIA' },
  { value: '마다가스카르', label: 'MADAGASCAR' },
  { value: '말라위', label: 'MALAWI' },
  { value: '말레이시아', label: 'MALAYSIA' },
  { value: '몰디브', label: 'MALDIVES' },
  { value: '말리', label: 'MALI' },
  { value: '몰타', label: 'MALTA' },
  { value: '마셜 제도', label: 'MARSHALL ISLANDS' },
  { value: '마르티니크', label: 'MARTINIQUE' },
  { value: '모리타니아', label: 'MAURITANIA' },
  { value: '모리셔스', label: 'MAURITIUS' },
  { value: '마요트', label: 'MAYOTTE' },
  { value: '멕시코', label: 'MEXICO' },
  { value: '미크로네시아 연방', label: 'MICRONESIA, FEDERATED STATES OF' },
  { value: '몰도바', label: 'MOLDOVA' },
  { value: '모나코', label: 'MONACO' },
  { value: '몽골', label: 'MONGOLIA' },
  { value: '몬테네그로', label: 'MONTENEGRO' },
  { value: '몬세라트', label: 'MONTSERRAT' },
  { value: '모로코', label: 'MOROCCO' },
  { value: '모잠비크', label: 'MOZAMBIQUE' },
  { value: '미얀마', label: 'MYANMAR' },
  { value: '나미비아', label: 'NAMIBIA' },
  { value: '나우루', label: 'NAURU' },
  { value: '네팔', label: 'NEPAL' },
  { value: '네덜란드', label: 'NETHERLANDS' },
  { value: '네덜란드령 안틸레스', label: 'NETHERLANDS ANTILLES' },
  { value: '뉴 칼레도니아', label: 'NEW CALEDONIA' },
  { value: '뉴질랜드', label: 'NEW ZEALAND' },
  { value: '니카라과', label: 'NICARAGUA' },
  { value: '니제르', label: 'NIGER' },
  { value: '나이지리아', label: 'NIGERIA' },
  { value: '니우에', label: 'NIUE' },
  { value: '노퍽 섬', label: 'NORFOLK ISLAND' },
  { value: '북마리아나 제도', label: 'NORTHERN MARIANA ISLANDS' },
  { value: '노르웨이', label: 'NORWAY' },
  { value: '오만', label: 'OMAN' },
  { value: '파키스탄', label: 'PAKISTAN' },
  { value: '팔라우', label: 'PALAU' },
  { value: '팔레스타인', label: 'PALESTINIAN TERRITORY, OCCUPIED' },
  { value: '파나마', label: 'PANAMA' },
  { value: '파푸아뉴기니', label: 'PAPUA NEW GUINEA' },
  { value: '파라과이', label: 'PARAGUAY' },
  { value: '페루', label: 'PERU' },
  { value: '필리핀', label: 'PHILIPPINES' },
  { value: '핏케언', label: 'PITCAIRN' },
  { value: '폴란드', label: 'POLAND' },
  { value: '포르투갈', label: 'PORTUGAL' },
  { value: '푸에르토리코', label: 'PUERTO RICO' },
  { value: '카타르', label: 'QATAR' },
  { value: '레위니옹', label: 'REUNION' },
  { value: '루마니아', label: 'ROMANIA' },
  { value: '러시아 연방', label: 'RUSSIAN FEDERATION' },
  { value: '르완다', label: 'RWANDA' },
  { value: '세인트 헬레나', label: 'SAINT HELENA' },
  { value: '세인트 키츠 네비스', label: 'SAINT KITTS AND NEVIS' },
  { value: '세인트 루시아', label: 'SAINT LUCIA' },
  { value: '세인트 피에르 미퀠론', label: 'SAINT PIERRE AND MIQUELON' },
  { value: '세인트 빈센트 그레나딘', label: 'SAINT VINCENT AND THE GRENADINES' },
  { value: '사모아', label: 'SAMOA' },
  { value: '산 마리노', label: 'SAN MARINO' },
  { value: '상투메 프린시페', label: 'SAO TOME AND PRINCIPE' },
  { value: '사우디아라비아', label: 'SAUDI ARABIA' },
  { value: '세네갈', label: 'SENEGAL' },
  { value: '세르비아', label: 'SERBIA' },
  { value: '세이셸', label: 'SEYCHELLES' },
  { value: '시에라리온', label: 'SIERRA LEONE' },
  { value: '싱가포르', label: 'SINGAPORE' },
  { value: '슬로바키아', label: 'SLOVAKIA' },
  { value: '슬로베니아', label: 'SLOVENIA' },
  { value: '솔로몬 제도', label: 'SOLOMON ISLANDS' },
  { value: '소말리아', label: 'SOMALIA' },
  { value: '남아프리카', label: 'SOUTH AFRICA' },
  { value: '사우스 조지아 사우스 샌드위치 제도', label: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' },
  { value: '스페인', label: 'SPAIN' },
  { value: '스리랑카', label: 'SRI LANKA' },
  { value: '수단', label: 'SUDAN' },
  { value: '수리남', label: 'SURINAME' },
  { value: '스발바르 제도 및 얀 마옌', label: 'SVALBARD AND JAN MAYEN' },
  { value: '스와질랜드', label: 'SWAZILAND' },
  { value: '스웨덴', label: 'SWEDEN' },
  { value: '스위스', label: 'SWITZERLAND' },
  { value: '시리아', label: 'SYRIAN ARAB REPUBLIC' },
  { value: '타이완', label: 'TAIWAN' },
  { value: '타지키스탄', label: 'TAJIKISTAN' },
  { value: '탄자니아', label: 'TANZANIA' },
  { value: '태국', label: 'THAILAND' },
  { value: '동티모르', label: 'TIMOR-LESTE' },
  { value: '토고', label: 'TOGO' },
  { value: '토켈라우', label: 'TOKELAU' },
  { value: '통가', label: 'TONGA' },
  { value: '트리니다드 토바고', label: 'TRINIDAD AND TOBAGO' },
  { value: '튀니지', label: 'TUNISIA' },
  { value: '터키', label: 'TURKEY' },
  { value: '투르크메니스탄', label: 'TURKMENISTAN' },
  { value: '투발루', label: 'TUVALU' },
  { value: '우간다', label: 'UGANDA' },
  { value: '우크라이나', label: 'UKRAINE' },
  { value: '아랍 에미리트', label: 'UNITED ARAB EMIRATES' },
  { value: '영국', label: 'UNITED KINGDOM' },
  { value: '미국', label: 'UNITED STATES' },
  { value: '미국령 군소 제도', label: 'UNITED STATES MINOR OUTLYING ISLANDS' },
  { value: '우루과이', label: 'URUGUAY' },
  { value: '우즈베키스탄', label: 'UZBEKISTAN' },
  { value: '바누아투', label: 'VANUATU' },
  { value: '베네수엘라', label: 'VENEZUELA' },
  { value: '베트남', label: 'VIETNAM' },
  { value: '영국령 버진 제도', label: 'VIRGIN ISLANDS, BRITISH' },
  { value: '미국령 버진 제도', label: 'VIRGIN ISLANDS, U.S.' },
  { value: '서부 사하라', label: 'WESTERN SAHARA' },
  { value: '예멘', label: 'YEMEN' },
  { value: '잠비아', label: 'ZAMBIA' },
  { value: '짐바브웨', label: 'ZIMBABWE' },
];
